

#NumPy
 is a Python library used for scientific and numerical computing. It provides a special type of object called an ndarray, which is like a powerful, fast version of a list, but for handling numbers.

#Key Points:

- NumPy arrays (ndarrays) store data in a fixed size and all items must be of the same type (e.g., all integers or all floats).

- Unlike regular Python lists, NumPy arrays are more efficient and faster for handling large sets of numbers.

- NumPy also includes many tools to do math, statistics, and other complex operations easily.

- Many scientific Python libraries use NumPy arrays because they make calculations much faster and easier.

- In short: NumPy helps you work with large amounts of numerical data quickly and efficiently.

#Creating Numpy Array

In [2]:
import numpy as np
'''

'''
a = np.array(range(1,11))  #-> as arguement we can give any sequence arguement
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2d and 3d Numpy array

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
#dtype
b = np.array([1,2,3] , dtype=float) #-> in dtype we can give any datatype of python
print(b)




[1. 2. 3.]


In [ ]:
#np.arange

np.arange(1,11) #-> similar like range sequence but here it creates numpy array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# with reshape
print(np.arange(1,11)) #-> now  lets now i want to reshape it
np.arange(1,10).reshape(3,3) #-> now it ir is reshaped 3 rows , 3 columns
                             #-> .reshape(nrows, ncolumns)



[ 1  2  3  4  5  6  7  8  9 10]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# np.ones and np.zeros

'''
.ones  method makes a array filled with ones takes aguement (rows,columns) as tuple
.zeros method makes a array filled with zerosntakes aguement (rows,columns) as tuple

'''

print(np.ones((3,4)))
print(np.zeros((3,4)))
print(np.ones.__doc__)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__arr

In [ ]:
# np.random

a = np.random.random((3,4))
b = np.random.randint(0,10,size = (3,3)) #can be
print(a)
print(b)
print(np.random.__doc__)

[[0.81249719 0.93351831 0.26818819 0.1404531 ]
 [0.31349232 0.22313457 0.41529506 0.74601593]
 [0.07158557 0.61950966 0.95593966 0.85731234]]
[[9 9 1]
 [2 9 1]
 [8 0 3]]

Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerator
--------------------------------------------

In [ ]:
# np.linspace() -> Creates a numpy array where each point is in equal distances
# .linspace(lower_range , upperrange , number of points)

print(np.linspace(-10,10,10))
print(np.linspace(-10,10,10,dtype=int))



[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
#n p.identity -> creates identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#Numpy class Properties

Numpy Objects has some propreties which can be get .

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim -> gives dimension
a3.ndim

3

In [ ]:
# shape -> gives shape

print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size -> returns total element

print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize -> how much memory taken by array

a3.itemsize

8

In [ ]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


# Changing Datatype

In [ ]:
#as type

a3.astype(np.int32) # C

# Array Operations


In [7]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1,a2,sep="\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
'''
Scalar Operations ,addition , multipication , substraction , divison , **exponent

'''

# Arithmetic

a3 = a1 + 5  # -> Addition is Supported
print(a3)


#relational operators

print(a2 > 5) # Checks every Element in Matrices is Greater than 5 .
print(a2==16)





[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [ True False False False]
 [False False False False]]


In [17]:
# Vector Operations
print(a1 + a2, a1 - a2 , a1 *a2 , a1//a2 , sep="\n")

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#Array Functions

In [23]:
a1 = np.random.random((3,4))
print(a1)

a1 = np.round(a1*100)
a1

[[0.88444163 0.17295448 0.93382551 0.94703429]
 [0.48338267 0.79491525 0.3992041  0.07617776]
 [0.40473245 0.38103113 0.07955507 0.06669374]]


array([[88., 17., 93., 95.],
       [48., 79., 40.,  8.],
       [40., 38.,  8.,  7.]])

In [32]:
'''
Aggregate Functions in a single array

max
min
sum
prod

'''

print((np.max(a1)))
print(np.sum(a1))
print(np.min(a1))
print(np.prod(a1))

'''
What if Someone said i want aggregate with in a Row or column
axis 0 -> column
axis = 1 -> row
'''

print(np.max(a1,axis=1))
print(np.sum(a1,axis=1))
print(np.min(a1,axis=1))
print(np.prod(a1,axis=1))


95.0
561.0
7.0
1.365174191259648e+18
[95. 79. 40.]
[293. 175.  93.]
[17.  8.  7.]
[13217160.  1213440.    85120.]


In [36]:
'''
Statistics Operations
mean
median
std
var

What if Someone said i want aggregate with in a Row or column
axis 0 -> column
axis = 1 -> row

'''

print(np.mean(a1))
print(np.median(a2))
print(np.std(a1))



46.75
17.5
32.71881466883135


In [ ]:
'''
Trigo Functions
Not much useful

'''

np.sin(a1)


In [41]:
'''
Dot Product -> MatriX Multipication
here
Row of a1 = Column of a2

'''

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print(a1,a2,sep="\n")

np.dot(a1,a2)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [43]:
'''
Log and  Exponents

'''

np.log(a1)
np.exp(a2)



/tmp/ipython-input-43-3653093884.py:6: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [45]:
'''
round
floor
ceil

'''


np.round(np.random.random((3,4)))
np.floor(np.random.random((3,4)))
np.ceil(np.random.random((3,4)))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#Indexing and Slicing

In [50]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [57]:
'''
Simple 1d array we Access elements by simple array

'''

print(a1)
print(a1[3])
print(a1[-1])
print(a1[0:3])
print(a1[0::2])


[0 1 2 3 4 5 6 7 8 9]
3
9
[0 1 2]
[0 2 4 6 8]


In [87]:
#2d

print(a2)
print(a2[1,2]) #-> A2[ROW,COLUMN] tO Access Elements
print(a2[1:9]) # -> Slicing is Done Linearly 🔍 Explanation:

a2[0:2,0:2] #-> a2[start_row:end_row, start_col:end_col]
print(a2[1:3,1:3])


print(a2[::2,1::2])
print(a2[1,::3])
print(a2[:2,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [94]:
print(a3)
print(a3[1,0,1]) # -> A3[NO_OF WHICH 2D ARRAY , ROW , THEN COLUMN]
print(a3[0,0,0])
'''
Koto number 2d array te ache ?
then
2D array Te koto number row and column ai ache

'''
#Slicing

a3 = np.arange(27).reshape(3,3,3)
print(a3)

print(a3[1][1:3,1:3])



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
10
0
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[13 14]
 [16 17]]


In [95]:
a3[::2,0,0:3:2] #a3[depth,row,column]

array([[ 0,  2],
       [18, 20]])

#Iterating

In [98]:
#1d
print(a1)

for i in a1:
  print(i,end=" ")


[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 

In [103]:
#2d
print(a2)

for i in a2: # one time ai one row print hoy
  print(i)

for i in np.nditer(a2): #np.nditer() using we access any element one by one
  print(i,end=" ")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 

In [104]:
#3d

for i in a3:
  print(i)

for i in np.nditer(a3): #np.nditer  using we access any element one by one
  print(i,end=" ")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

#Shaping

In [ ]:
# np.reshape() function we learned earlier

In [106]:

# Transpose
print(a2)
print(np.transpose(a2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [107]:
#Ravel

'''
Changes Matrices to 1d array
'''
print(np.ravel(a3))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


#Stacking

In [115]:
'''

We can merge Two Arrays

There are two ways we can stack two arrays

-- Horizontally
-- Vertically

method -->

np.hstack((a1,a2,a3,....))  -> tuple of arrays will go as Arguement
np.vstack((a1,a2,a3,.....))

'''

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

print()

print("Horizontal Join ->",sep = " ")
print(np.hstack((a4,a5)))

print()

print("Vertical Join ->",sep = " ")
print(np.vstack((a4,a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Horizontal Join ->
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

Vertical Join ->
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


# Spliting

In [120]:
'''
Oppsite of Stacking

here we  Split our Arrays

np.hsplit(arrayName,number of Arrays you want to split) -> Split Array Vertically
np.vsplit(arrayName,number of Arrays you want to split) -> Split Array horizontally

'''

print(a4)

print(np.hsplit(a4,2))


print(np.vsplit(a4,1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
